### ISSUE TITLE
Update cs-studio common product to work with the new master

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/org.csstudio.product#14]
- [x] diirt integration
- [x] new target #11

**Comment by kasemir** [comment]
Related/details:

`org.csstudio.diirt.util.preferences/preferences.ini` is not included in the build (missing from `build.properties`)

common product/diirt/* example files use  `diirt/support/ca/ca.xml`. What's actually used seems to be `diirt/datasources/ca/ca.xml`.

Preference `org.csstudio.diirt.util.preferences/diirt.home` needs some way to configure a diirt root that is an absolute location (done), but also a location relative to the install or instance location.
For example:
````
org.csstudio.diirt.util.preferences/diirt.home=/etc/diirt
org.csstudio.diirt.util.preferences/diirt.home=${user.home}/.diirt
org.csstudio.diirt.util.preferences/diirt.home=${osgi.install.area}/diirt
org.csstudio.diirt.util.preferences/diirt.home=${osgi.configuration.area}/diirt
org.csstudio.diirt.util.preferences/diirt.home=${osgi.instance.area}/diirt
````

**Comment by shroffk** [comment]
Ya I noticed the diirt/support/ca/ca.xml is not being used...I am fixing that

**Comment by kasemir** [comment]
See https://github.com/ControlSystemStudio/cs-studio/issues/1406
