### ISSUE TITLE
Fresh install compilation error 

### ISSUE THREAD

**Issue by mbeldis** [ControlSystemStudio/org.csstudio.product#29]
Trying to compile from clean checkout and getting:

-----

[INFO] --- tycho-p2-repository-plugin:1.0.0:assemble-repository (default-assemble-repository) @ repository ---
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from cs-studio 4.5.1 to org.csstudio.core.diirt.feature.feature.group [0.0.1.201708041805].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from cs-studio 4.5.1 to org.csstudio.core.diirt.feature.feature.group [0.0.1.201708041805].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from cs-studio 4.5.1 to org.csstudio.core.diirt.feature.feature.group [0.0.1.201708041805].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
[INFO] 
[INFO] --- tycho-p2-repository-plugin:1.0.0:archive-repository (default-archive-repository) @ repository ---
[INFO] Building zip: /home/rpiuser/Work/org.csstudio.product/repository/target/repository-4.5.1-SNAPSHOT.zip
[INFO] 
[INFO] --- tycho-p2-director-plugin:1.0.0:materialize-products (materialize-products) @ repository ---
[INFO] Installing product cs-studio for environment linux/gtk/x86_64 to /home/rpiuser/Work/org.csstudio.product/repository/target/products/cs-studio/linux/gtk/x86_64/cs-studio
Installing cs-studio 4.5.1.
Installation failed.
Cannot complete the install because one or more required items could not be found.
 Software being installed: Cs-studio 4.5.1 (cs-studio 4.5.1)
 Missing requirement: Cs-studio 4.5.1 (cs-studio 4.5.1) requires 'org.csstudio.core.diirt.feature.feature.group [0.0.1.201708041805]' but it could not be found
Application failed, log file location: /home/rpiuser/Work/org.csstudio.product/workspace/.metadata/.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] product ........................................... SUCCESS [0.289s]
[INFO] products-csstudio-plugins ......................... SUCCESS [0.000s]
[INFO] org.csstudio.product .............................. SUCCESS [3.773s]
[INFO] org.csstudio.startup.intro ........................ SUCCESS [0.597s]
[INFO] products-csstudio-features ........................ SUCCESS [0.000s]
[INFO] org.csstudio.product.feature ...................... SUCCESS [0.289s]
[INFO] org.csstudio.product.configuration.feature ........ SUCCESS [0.142s]
[INFO] repository ........................................ FAILURE [20.703s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9:22.905s
[INFO] Finished at: Mon Aug 07 10:21:25 BST 2017
[INFO] Final Memory: 170M/423M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-director-plugin:1.0.0:materialize-products (materialize-products) on project repository: Installation of product cs-studio for environment linux/gtk/x86_64 failed: Call to p2 director application failed with exit code 13. Program arguments were: [-metadataRepository, file:/home/rpiuser/Work/org.csstudio.product/repository/target/,file:/home/rpiuser/Work/org.csstudio.product/repository/target/targetPlatformRepository/, -artifactRepository, file:/home/rpiuser/Work/org.csstudio.product/repository/target/,file:/resolution-context-artifacts@%252Fhome%252Frpiuser%252FWork%252Forg.csstudio.product%252Frepository,file:/home/rpiuser/Work/org.csstudio.product/repository/target/,file:/home/rpiuser/Work/org.csstudio.product/features/org.csstudio.product.feature/target/,file:/home/rpiuser/Work/org.csstudio.product/features/org.csstudio.product.configuration.feature/target/,file:/home/rpiuser/Work/org.csstudio.product/plugins/org.csstudio.product/target/,file:/home/rpiuser/Work/org.csstudio.product/plugins/org.csstudio.startup.intro/target/,file:/home/rpiuser/.m2/repository/, -installIU, cs-studio, -destination, /home/rpiuser/Work/org.csstudio.product/repository/target/products/cs-studio/linux/gtk/x86_64/cs-studio, -profile, DefaultProfile, -profileProperties, org.eclipse.update.install.features=true, -roaming, -p2.os, linux, -p2.ws, gtk, -p2.arch, x86_64]. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :repository

**Comment by kasemir** [comment]
Not sure how exactly you're trying to build, and when you depend on remote maven repositories, the results can be unpredictable.

Since your error message is related to diirt: There has been a change in the repository that we use for diirt. We've reverted from the ControlSystemStudio/diirt fork back to the original diirt/diirt.

The SNS product contains an example for fetching all sources and building then building them as much as possible locally: https://github.com/ControlSystemStudio/org.csstudio.sns/tree/master/build
You might try that, which should at this time succeed, and then compare with your current build setup and see where it differs and then fails.

**Comment by mbeldis** [comment]
I work with Virtual Machines. So after a fresh install of Scientific Linux 7 i do:

yum install git maven; the latter installs also java 1.8.
git clone https://github.com/ControlSystemStudio/org.csstudio.product.git
cd  org.studio.product directory
mvn clean verify

And I expect this to work and it works now.

Thank you to everyone involved.

**Comment by berryma4** [comment]
This was probably solved because we merged the following pull request:
https://github.com/ControlSystemStudio/org.csstudio.product/pull/28
It's a work around, but we decided to merge it at the last meeting until we understand why.
